//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace emarket.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public int id { get; set; }

        [Required(ErrorMessage = "You have to enter  Name Product")]
        public string name { get; set; }


        [Required(ErrorMessage = "You have to enter Price Product ")]
        public Nullable<int> price { get; set; }


        public string image { get; set; }

        [Required(ErrorMessage = "You have to enter  Description Product ")]
        public string description { get; set; }
        [Required(ErrorMessage = "You have to enter  Category Product ")]
        public Nullable<int> category_id { get; set; }

        public virtual Category Category { get; set; }
    }
}
